version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    volumes:
      - .:/app  # Mount the current directory to /app in the container
